eshop/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'
  get '/pages/contact' => 'pages#contact'

  resources :users, :except => [:destroy]
  get '/users/edit' => 'users#edit'

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/products/:id/purchase' => 'products#purchase_stock', :as => 'purchase_stock'
  patch '/products/:id/add' => 'products#add_stock', :as => 'add_stock'
  resources :products, :except => [:destroy]

  get '/order/:id/update' => 'orders#update', :as => 'update_order'
  resources :orders, :except => [:destroy, :create]

  resources :businesses, :only => [:show, :edit, :update]

  get '/cart' => 'line_item#index'
  get '/cart/add' => 'line_item#add_cart'
  put '/cart/:id/:sign' => 'line_item#change_qty', :as => 'update_item'
  delete '/cart/:id' => 'line_item#destroy', :as => 'delete_item'
  delete '/cart/:id/all' => 'line_item#destroy_cart', :as => 'delete_cart'
  resources :line_items

  get '/reports/inventory' => 'reports#inventory'
  get '/reports/sales' => 'reports#sales'
  get '/reports/profit' => 'reports#profit'
  get '/reports/shipping' => 'reports#shipping'
  get '/reports/finalise' => 'reports#finalise'

  resources :charges

end

eshop/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  name            :text
#  inventory       :integer
#  unit_cost_price :float
#  description     :text
#  price_regular   :float
#  tax_applies     :boolean          default(TRUE)
#  price_sale      :float
#  on_sale         :boolean          default(FALSE)
#  business_id     :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image           :text
#  tags            :text
#  active          :boolean          default(TRUE)
#

class Product < ActiveRecord::Base

  belongs_to :business
  has_many :line_items

def self.search(search)
  where("name ILIKE ? or description ILIKE ? or tags ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%" )
end

end

eshop/app/controllers/products_controller.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  name            :text
#  inventory       :integer
#  unit_cost_price :float
#  description     :text
#  price_regular   :float
#  tax_applies     :boolean          default(TRUE)
#  price_sale      :float
#  on_sale         :boolean          default(FALSE)
#  business_id     :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image           :text
#  tags            :text
#  active          :boolean          default(TRUE)
#

class ProductsController < ApplicationController
  def index
    if params[:search]
      @products = Product.search(params[:search]).where(:active => true).sort
    elsif @current_user.present? && @current_user.admin?
      @products = Product.all
    else
      @products = Product.where(:active => true).sort
    end
  end

  def new
    @product = Product.new
  end

  def create
    req = Cloudinary::Uploader.upload( params[:product][:image])
    product = Product.create product_params
    product.image = req["url"]
    product.save
    redirect_to product
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    if params[:product][:image].present?
      req = Cloudinary::Uploader.upload( params[:product][:image])
    end
    product = Product.find params[:id]
    product.image["req"]
    product.update product_params
    redirect_to product
  end

  def show
    @product = Product.find params[:id]
  end

  def purchase_stock
    @product = Product.find params[:id]
  end

  def add_stock
    quantity = product_params.first.last.to_f
    cost = product_params.sort[1].last.to_f
    product_existing = Product.find params[:id]
    current_inventory = product_existing.inventory
    current_unit_cost_price = product_existing.unit_cost_price
    total_cost = current_inventory * current_unit_cost_price + quantity * cost
    product_existing.inventory = quantity + current_inventory
    product_existing.unit_cost_price = total_cost / (current_inventory + quantity)
    product_existing.save
    redirect_to product_path
  end


  private
  def product_params
    params.require(:product).permit(:name, :inventory, :unit_cost_price, :description, :price_regular, :tax_applies, :price_sale, :on_sale, :business_id, :search, :tags, :active, :image)
  end
end

eshop/app/helpers/products_helper.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  name            :text
#  inventory       :integer
#  unit_cost_price :float
#  description     :text
#  price_regular   :float
#  tax_applies     :boolean          default(TRUE)
#  price_sale      :float
#  on_sale         :boolean          default(FALSE)
#  business_id     :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image           :text
#  tags            :text
#  active          :boolean          default(TRUE)
#

module ProductsHelper
end

eshop/app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>

<fieldset>
  <%= f.label :name %>
  <%= f.text_field :name %>
</fieldset>
<fieldset>
  <%= f.label :tags %>
  <%= f.text_field :tags %>
</fieldset>
<fieldset>
  <%= f.label :desciption %>
  <%= f.text_field :description %>
</fieldset>
<fieldset>
  <%= f.label :price_regular %>
  <%= f.text_field :price_regular %>
</fieldset>
<fieldset>
  <%= f.label :price_sale %>
  <%= f.text_field :price_sale %>
</fieldset>
<fieldset class="image-add-field">
  <%= f.label :image %>
  <%= f.file_field :image %>
</fieldset>
<fieldset>
  <%= f.label :on_sale %>
  <%= f.check_box :on_sale %>
</fieldset>
<fieldset>
  <%= f.label :tax_applies %>
  <%= f.check_box :tax_applies %>
</fieldset>
<fieldset>
  <%= f.label :active %>
  <%= f.check_box :active %>
</fieldset>
<fieldset>
  <%= f.hidden_field :business_id, :value => Business.first.id %>
  <%= f.hidden_field :inventory, :value => 0 %>
  <%= f.hidden_field :unit_cost_price, :value => 0 %>
  <%= f.submit %>
</fieldset>

<% end %>

eshop/app/views/products/edit.html.erb
<div class="admin">
<h1>Edit Product</h1>

<%= render :partial => 'form' %>
</div>

eshop/app/views/products/index.html.erb
<div class="row">
    <% @products.each do |product| %>
        <div class='col-md-3 col-sm-4 col-xs-12'>
            <div class='product-index-container'>
                <div class='index-image-wrapper'>
                    <%= link_to(image_tag(product.image, :class => "index-image"), product) %>
                </div>
                <br>
                <h2><%= link_to product.name, product, :class => "product-text" %></h2>
                <br>
                <% unless product.on_sale? %>
                    <h2><%= number_to_currency(product.price_regular) %></h2>
                    <br>
                <% end %>
                <% if product.on_sale? %>
                    <p class='product-sale product-text'><%= number_to_currency(product.price_regular) %></p>
                    <p class='product-text'><%= number_to_currency(product.price_sale) %></p>
                <% end %>
                <% if @current_user.present?%>
                    <% if product.active.blank? %>
                        <p><%= button_tag "Inactive" %></p>
                    <% elsif product.inventory != 0  %>
                        <p><%= link_to (button_tag "Add to Cart"), cart_add_path(:id => product.id, :page => 'index') %></p>
                    <% elsif product.inventory == 0 %>
                        <p><%= button_tag "Out of Stock" %></p>
                    <% end %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

eshop/app/views/products/new.html.erb
<div class="admin">
<h1>Add New Product</h1>

<%= render :partial => 'form' %>
</div>

eshop/app/views/products/purchase_stock.html.erb
<div class="admin">
<h1>Purchase Stock</h1>

<%= image_tag @product.image, :class => "feature" %>
<p>Name: <%= @product.name %></p>
<%= form_for(@product, url: add_stock_path) do |f| %>
    <%= f.label :inventory %>
    <%= f.text_field :inventory %>
    <br>
    <%= f.label :unit_cost_price %>
    <%= f.text_field :unit_cost_price %>
    <br>
    <%= f.submit %>
<% end %>
</div>

eshop/app/views/products/show.html.erb
<div class="admin">
<h1><%= @product.name %></h1>

<%= image_tag(@product.image, :class => "feature") %>
<% if @product.active.blank? %>
    <p><%= button_tag "Inactive" %></p>
<% elsif @current_user.present? && @product.inventory != 0 %>
    <p><%= link_to (button_tag "Add to Cart"), cart_add_path(:id => @product.id, :page => 'show') %></p>
<% elsif @product.inventory == 0 %>
    <p><%= button_tag "Out of Stock" %></p>
<% end %>
<% unless @product.on_sale? %>
    <p>Price: <%= number_to_currency(@product.price_regular) %></p>
<% end %>
<% if @product.on_sale? %>
    <p class="product-sale">Price: <%= number_to_currency(@product.price_regular) %></p>
    <p>Sale Price: <%= number_to_currency(@product.price_sale) %></p>
    <%  %>
    <%  %>
<% end %>
<p>Description: <%= @product.description %></p>
<% if @current_user.present? %>
    <% if @current_user.admin? %>
        <p>Tags: <%= @product.tags %></p>
        <p>Stock Available: <%= @product.inventory %></p>
        <p>Cost Price: <%= number_to_currency(@product.unit_cost_price) %></p>
        <p>Regular Price: <%= number_to_currency(@product.price_regular) %></p>
        <p>Sale Price: <%= number_to_currency(@product.price_sale) %></p>
        <p>Currently on sale: <%= @product.on_sale %></p>
        <p>Taxed: <%= @product.tax_applies %></p>
        <%= link_to "Edit Product", edit_product_path %>
        <%= link_to "Add Stock", purchase_stock_path %>
    <% end %>
    <% if @current_user.master? %>
        <p>Business: <%= @product.business_id %></p>
    <% end %>
<% end %>
</div>