eshop/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'
  get '/pages/contact' => 'pages#contact'

  resources :users, :except => [:destroy]
  get '/users/edit' => 'users#edit'

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/products/:id/purchase' => 'products#purchase_stock', :as => 'purchase_stock'
  patch '/products/:id/add' => 'products#add_stock', :as => 'add_stock'
  resources :products, :except => [:destroy]

  get '/order/:id/update' => 'orders#update', :as => 'update_order'
  resources :orders, :except => [:destroy, :create]

  resources :businesses, :only => [:show, :edit, :update]

  get '/cart' => 'line_item#index'
  get '/cart/add' => 'line_item#add_cart'
  put '/cart/:id/:sign' => 'line_item#change_qty', :as => 'update_item'
  delete '/cart/:id' => 'line_item#destroy', :as => 'delete_item'
  delete '/cart/:id/all' => 'line_item#destroy_cart', :as => 'delete_cart'
  resources :line_items

  get '/reports/inventory' => 'reports#inventory'
  get '/reports/sales' => 'reports#sales'
  get '/reports/profit' => 'reports#profit'
  get '/reports/shipping' => 'reports#shipping'
  get '/reports/finalise' => 'reports#finalise'

  resources :charges

end

eshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>

    <nav>
        <%= link_to"Home", root_path, :class => "nav-link" %>
        <%= link_to "Contact Us", pages_contact_path, :class => "nav-link" %>
        <% if @current_user.present? %>
            <%= link_to "Edit profile", edit_user_path(@current_user), :class => "nav-link" %>
            <%= link_to "Logout #{ @current_user.email}", login_path, :method => :delete, :class => "nav-link" %>
        <% else %>
            <%= link_to "Signup", signup_path, :class => "nav-link" %>
            <%= link_to "Login", login_path, :class => "nav-link"  %>
        <% end %>
    </nav>

    <div class="container-fluid search-nav">
      <div class='row search-nav-wrapper'>
        <%= form_tag(products_path, :method => "get", id: "search-form") do %>
            <div class="col-lg-3 col-sm-3"><%= link_to(image_tag(Business.first.logo, :id => "business-logo"), root_path) %></div>
            <div class="col-lg-7 col-sm-9">
                <div class="row">
                    <div class="col-lg-8 col-sm-8"><%= text_field_tag :search, params[:search], placeholder: "Search Products", :class => "form-control", id: "product-search-field" %></div>
                    <div class="col-lg-4 col-sm-4"><%= submit_tag "Search", :class => "btn btn-default", id: "product-search-button" %></div>
                </div>
            </div>
        <% end %>
        <div class="col-lg-2 col-sm-4"><%= link_to(button_tag('Shopping Cart', :class => "btn btn-default", :id => 'cart-button'), cart_path) %></div>
      </div>
    </div>

    <div class='main-menu-wrapper'>
      <div class='main-menu-list row'>
        <% if @current_user.nil? %>
            <div class="col-lg-1 col-md-1 col-sm-0 col-xs-0"></div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6"><%= link_to(button_tag("All Products", :class => "menu-button"), products_path) %></div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6"><%= link_to(button_tag("Retro Candy", :class => "menu-button"), products_path(:search => "retro")) %></div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6"><%= link_to(button_tag("Chocolate", :class => "menu-button"), products_path(:search => "chocolate")) %></div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6"><%= link_to(button_tag("Gum", :class => "menu-button"), products_path(:search => "gum")) %></div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6"><%= link_to(button_tag("Lollipops", :class => "menu-button"), products_path(:search => "lollipop")) %></div>
            <div class="col-lg-1 col-md-1 col-sm-0 col-xs-0"></div>
        <% elsif @current_user.present? && @current_user.admin.blank? %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("All Products", :class => "menu-button"), products_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Retro Candy", :class => "menu-button"), products_path(:search => "retro")) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Chocolate", :class => "menu-button"), products_path(:search => "chocolate")) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Gum", :class => "menu-button"), products_path(:search => "gum")) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Lollipops", :class => "menu-button"), products_path(:search => "lollipop")) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Previous Orders", :class => "menu-button"), orders_path) %></div>
        <% elsif @current_user.admin? %>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("All Products", :class => "menu-button"), products_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Add Product", :class => "menu-button"), new_product_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("All Users", :class => "menu-button"), users_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("All Orders", :class => "menu-button"), orders_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Sales", :class => "menu-button"), reports_sales_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Profit", :class => "menu-button"), reports_profit_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Inventory", :class => "menu-button"), reports_inventory_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Shipping", :class => "menu-button"), reports_shipping_path) %></div>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Finalise", :class => "menu-button"), reports_finalise_path) %></div>
        <% end %>
        <% if @current_user.present? && @current_user.master? %>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6"><%= link_to(button_tag("Business", :class => "menu-button"), business_path(@current_user.business_id)) %></div>
        <% end %>
      </div>
    </div>

  </header>

  <div class='main-area'>
    <% if flash[:error].present? %>
      <h2 class='error'>
        <%= flash[:error] %>
      </h2>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>