eshop/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'
  get '/pages/contact' => 'pages#contact'

  resources :users, :except => [:destroy]
  get '/users/edit' => 'users#edit'

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/products/:id/purchase' => 'products#purchase_stock', :as => 'purchase_stock'
  patch '/products/:id/add' => 'products#add_stock', :as => 'add_stock'
  resources :products, :except => [:destroy]

  get '/order/:id/update' => 'orders#update', :as => 'update_order'
  resources :orders, :except => [:destroy, :create]

  resources :businesses, :only => [:show, :edit, :update]

  get '/cart' => 'line_item#index'
  get '/cart/add' => 'line_item#add_cart'
  put '/cart/:id/:sign' => 'line_item#change_qty', :as => 'update_item'
  delete '/cart/:id' => 'line_item#destroy', :as => 'delete_item'
  delete '/cart/:id/all' => 'line_item#destroy_cart', :as => 'delete_cart'
  resources :line_items

  get '/reports/inventory' => 'reports#inventory'
  get '/reports/sales' => 'reports#sales'
  get '/reports/profit' => 'reports#profit'
  get '/reports/shipping' => 'reports#shipping'
  get '/reports/finalise' => 'reports#finalise'

  resources :charges

end

eshop/app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  quantity   :integer
#  unit_cost  :float
#  unit_tax   :float
#  order_id   :integer
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  unit_price :float
#

class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :user
end

eshop/app/controllers/line_item_controller.rb
class LineItemController < ApplicationController

  before_action :require_login

  def index
    @cart_items = LineItem.where(:order_id => nil).where(:user_id => @current_user.id)
  end

  def add_cart
    product = Product.find params[:id]

    # If a person is not logged in
      # Set a temporary value on there (temp_cart_id) - get that from session[:temp_cart_id]


    # session[:cart_id] = "lskndlnskdkldn"

    line = LineItem.create :product_id => product.id, :quantity => 1, :user_id => @current_user.id, :unit_cost => product.unit_cost_price ,:unit_tax => 0
    if product.on_sale?
      line.unit_price = product.price_sale
    else
      line.unit_price = product.price_regular
    end
    unless product.tax_applies == false
      business = Business.find product.business_id
      line.unit_tax = line.unit_price - (line.unit_price * (1 - (1 / (1 + business.tax_rate))))
    end
    line.save
    if params[:page] == 'index'
        redirect_to products_path
    else
        redirect_to product_path(params[:id])
    end
  end

  def change_qty
    line = LineItem.find params[:id]
    product = Product.find line.product_id
    change = params[:sign]
    unless line.quantity >= product.inventory && change.to_i == 1
        line.quantity += change.to_i
        line.save
    end
    if line.quantity == 0
        line.destroy
    end
    redirect_to cart_path
  end

  def destroy
    line = LineItem.find params[:id]
    line.destroy
    redirect_to cart_path
  end

  def destroy_cart
    user = User.find params[:id]
    lines = LineItem.where(:user_id => user.id).where(:order_id => nil)
    lines.destroy_all
    redirect_to cart_path
  end

  private

  def require_login
    unless @current_user.present?
      flash[:error] = "Please login to add contents to your shopping cart"
      redirect_to login_path
    end
  end

end

eshop/app/helpers/line_item_helper.rb
module LineItemHelper
end

eshop/app/views/line_item/index.html.erb
<div class="admin">
<h1>Shopping Cart</h1>
<% @total_price = 0 %>
<% @total_tax = 0 %>
<ul>
  <% @cart_items.sort.each do |item| %>
    <% product = Product.find item.product_id %>
    <% @total_price += (item.unit_price * item.quantity) %>
    <% @total_tax += (item.unit_tax * item.quantity) %>
    <li>
      <%= image_tag product.image, :class => 'index-image' %>
      <p><%= product.name %></p>
      <p>Quantity: <%= item.quantity %>
        <%= link_to (button_tag "-"), update_item_path(:id => item.id, :sign => -1), :method => :put %>
        <%= link_to (button_tag "+"), update_item_path(:id => item.id, :sign => 1), :method => :put %></p>
      <p>Total Price: <%= number_to_currency(item.unit_price * item.quantity)  %></p>
      <p><%= link_to (button_tag "Remove from Cart"), delete_item_path(:id => item.id), :method => :delete %></p>
    </li>
  <% end %>
    <li>
      <p></p>
      <p>Grand Total: <%= number_to_currency(@total_price) %></p>
      <p>Includes GST: <%= number_to_currency(@total_tax) %></p>
      <p><%= link_to (button_tag "Clear Cart"), delete_cart_path(:id => @current_user.id), :method => :delete %></p>
      <p><%= link_to (button_tag "Purchase Items"), new_order_path %></p>
    </li>
</ul>
</div>