eshop/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'
  get '/pages/contact' => 'pages#contact'

  resources :users, :except => [:destroy]
  get '/users/edit' => 'users#edit'

  get '/signup' => 'users#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/products/:id/purchase' => 'products#purchase_stock', :as => 'purchase_stock'
  patch '/products/:id/add' => 'products#add_stock', :as => 'add_stock'
  resources :products, :except => [:destroy]

  get '/order/:id/update' => 'orders#update', :as => 'update_order'
  resources :orders, :except => [:destroy, :create]

  resources :businesses, :only => [:show, :edit, :update]

  get '/cart' => 'line_item#index'
  get '/cart/add' => 'line_item#add_cart'
  put '/cart/:id/:sign' => 'line_item#change_qty', :as => 'update_item'
  delete '/cart/:id' => 'line_item#destroy', :as => 'delete_item'
  delete '/cart/:id/all' => 'line_item#destroy_cart', :as => 'delete_cart'
  resources :line_items

  get '/reports/inventory' => 'reports#inventory'
  get '/reports/sales' => 'reports#sales'
  get '/reports/profit' => 'reports#profit'
  get '/reports/shipping' => 'reports#shipping'
  get '/reports/finalise' => 'reports#finalise'

  resources :charges

end

eshop/app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id               :integer          not null, primary key
#  invoice_number   :text
#  total_cost       :float
#  total_tax        :float
#  discount_amount  :float
#  user_id          :integer
#  order_status_id  :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  order_status     :text
#  purchase_date    :date
#  payment_date     :date
#  shipped_date     :date
#  finalised_date   :date
#  total_revenue    :float
#  delivery_address :text
#  shipping_id      :string
#

class Order < ActiveRecord::Base
  has_many :line_items
  belongs_to :user
end

eshop/app/controllers/orders_controller.rb
# == Schema Information
#
# Table name: orders
#
#  id               :integer          not null, primary key
#  invoice_number   :text
#  total_cost       :float
#  total_tax        :float
#  discount_amount  :float
#  user_id          :integer
#  order_status_id  :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  order_status     :text
#  purchase_date    :date
#  payment_date     :date
#  shipped_date     :date
#  finalised_date   :date
#  total_revenue    :float
#  delivery_address :text
#  shipping_id      :string
#

class OrdersController < ApplicationController
  before_action :authorise

  def index
    if @current_user.present? && @current_user.admin?
        @orders = Order.all
    elsif @current_user.present? && @current_user.admin.blank?
        @orders = Order.where(:user_id => @current_user.id)
    elsif params[:id].present?
        @orders = Order.where(:user_id => params[:id])
    else
        redirect_to root_path
    end
  end

  def new
      @cart_items = LineItem.where(:order_id => nil).where(:user_id => @current_user.id)
      @order = Order.create :user_id => @current_user.id
      total_price = 0
      total_tax = 0
      total_cost = 0
      @cart_items.each do |item|
          product = Product.find item.product_id
          product.inventory -= item.quantity
          product.save
          item.order_id = @order.id
          item.save
          total_price += (item.unit_price * item.quantity)
          total_tax += (item.unit_tax * item.quantity)
          total_cost += (item.unit_cost * item.quantity)
      end
      @order.total_revenue = total_price
      @order.total_tax = total_tax
      @order.total_cost = total_cost
      @order.purchase_date = DateTime.now
      @order.save
      @purchased_items = LineItem.where(:order_id => @order.id)
  end

  def edit
    @order = Order.find params[:id]
    @purchased_items = LineItem.where(:order_id => @order.id)
  end

  def show
    @order = Order.find params[:id]
    @customer = User.where(:order_id => @order.id)
    @purchased_items = LineItem.where(:order_id => @order.id)
  end

  def update
    order = Order.find params[:id]
    order.update order_params
    session[:order_id] = order.id
    if order.finalised_date.present?
        redirect_to reports_finalise_path
    elsif order.shipped_date.present?
        redirect_to reports_shipping_path
    elsif order.payment_date.nil?
        redirect_to new_charge_path
    else
        redirect_to order_path(order.id)
    end
  end

private
def authorise
  redirect_to root_path unless (@current_user.present?)
end

def order_params
  params.require(:order).permit(:purchase_date, :payment_date, :shipped_date, :finalised_date, :delivery_address, :shipping_id, :invoice_number)
end

end

eshop/app/helpers/orders_helper.rb
# == Schema Information
#
# Table name: orders
#
#  id               :integer          not null, primary key
#  invoice_number   :text
#  total_cost       :float
#  total_tax        :float
#  discount_amount  :float
#  user_id          :integer
#  order_status_id  :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  order_status     :text
#  purchase_date    :date
#  payment_date     :date
#  shipped_date     :date
#  finalised_date   :date
#  total_revenue    :float
#  delivery_address :text
#  shipping_id      :string
#

module OrdersHelper

  def order_status (id)
      order = Order.find id
      if order.finalised_date.present?
            order.order_status = "Order finalised"
      elsif order.shipped_date.present?
            order.order_status = "awaiting confirmation"
      elsif order.payment_date.present?
            order.order_status = "Awaiting shipment"
      else
            order.order_status = "Awaiting payment"
      end
      order.save
  end

end

eshop/app/views/orders/edit.html.erb
<div class="admin">
<% order_status(@order.id) %>
<h1>Update Order Status</h1>

<p>Order_id: <%= @order.id %></p>

<ul>
<% @purchased_items.each do |item| %>
      <li>
        <p>Product id: <%= item.product_id %></p>
        <p>Quantity: <%= item.quantity %></p>
        <p>Total Price: <%= number_to_currency(item.unit_cost * item.quantity)  %></p>
      </li>
<% end %>
      <li>
          <p>Total Price: <%= number_to_currency(@order.total_cost) %></p>
          <p>includes GST: <%= number_to_currency(@order.total_tax) %></p>
      </li>
</ul>
<p>Order Status: <%= @order.order_status %></p>
<%= form_for @order do |f| %>
      <%= f.label :purchased %>
      <%= f.date_field :purchase_date %>
      <br>
      <%= f.label :paid %>
      <%= f.date_field :payment_date %>
      <br>
      <%= f.label :shipped %>
      <%= f.date_field :shipped_date %>
      <br>
      <%= f.label :finalised %>
      <%= f.date_field :finalised_date %>
      <br>
      <%= f.submit %>
<% end %>
</div>

eshop/app/views/orders/index.html.erb
<div class="admin">
<h1>Orders</h1>

<% @orders.reverse_order.each do |order| %>
    <% order_status(order.id) %>
    <% if order.user_id.present? %>
        <% user = User.find order.user_id %>
    <% end %>
    <hr>
    <div class='order-index-line row'>
        <div class="col-sm-2">Invoice: <%= order.invoice_number %></div>
        <div class="col-sm-2">Date: <%= order.purchase_date %></div>
        <div class="col-sm-2">User: <%= user.name %></div>
        <div class="col-sm-2">Price: <%= number_to_currency(order.total_revenue) %></div>
        <div class="col-sm-3">Order Status: <%= order.order_status %></div>
        <div class="col-sm-1"><%= link_to(button_tag("View"), order_path(order.id)) %></div>
    </div>
<% end %>
</div>

eshop/app/views/orders/new.html.erb
<div class="admin">
<% order_status(@order.id) %>
<h1>Order</h1>

<ul>
<% @purchased_items.each do |item| %>
      <% product = Product.find item.product_id %>
      <li>
        <%= link_to(image_tag(product.image, :class => 'thumb'), product_path(product.id)) %>
        <p><%= product.name %></p>
        <p>Quantity: <%= item.quantity %></p>
        <p>Total Price: <%= number_to_currency(item.unit_price * item.quantity)  %></p>
      </li>
<% end %>
      <li>
          <p>Total Price: <%= number_to_currency(@order.total_revenue) %></p>
          <p>includes GST: <%= number_to_currency(@order.total_tax) %></p>
      </li>
</ul>

<%= form_for(@order) do |f| %>
      <%= f.label :delivery_address %>
      <%= f.text_field :delivery_address %>
      <br>
      <br>
      <% inv = 'INV' + @order.id.to_s.rjust(5, '0') %>
      <%= f.hidden_field :invoice_number, :value => inv %>
      <%= f.submit "Submit" %>
<% end %>
</div>

eshop/app/views/orders/show.html.erb
<div class="admin">
<% order_status(@order.id) %>
<h1>Order</h1>

<p>Date: <%= @order.purchase_date %></p>
<p>Invoice Number: <%= @order.invoice_number %></p>
<br>
<p>Name: <%= @customer.name %></p>
<p>Delivery Address: <%= @order.delivery_address %></p>

<ul>
<% @purchased_items.each do |item| %>
      <% product = Product.find item.product_id %>
      <li>
        <%= link_to(image_tag(product.image, :class => 'index-image'), product_path(product.id)) %>
        <p><%= product.name %></p>
        <p>Quantity: <%= item.quantity %></p>
        <p>Total Price: <%= number_to_currency(item.unit_price * item.quantity)  %></p>
      </li>
<% end %>
      <li>
          <p>Total Price: <%= number_to_currency(@order.total_revenue) %></p>
          <p>includes GST: <%= number_to_currency(@order.total_tax) %></p>
      </li>
</ul>
<p>Order Status: <%= @order.order_status %></p>
<p>Purchase Date: <%= @order.purchase_date %></p>
<p>Payment Date: <%= @order.payment_date %></p>
<p>Shipped Date: <%= @order.shipped_date %></p>
<p>Finalised Date: <%= @order.finalised_date %></p>

<% if @current_user.admin? %>
      <%= link_to(button_tag("Update Status"), edit_order_path(@order.id) ) %>
<% end %>
</div>